name: Sync Cloudflare Split Tunnels

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run sync script
        env:
          # 这里对应你在 GitHub Secrets 设置的两个名称
          CF_API_TOKEN: ${{ secrets.cfat_Y8mLtKHpGAwYk9cXlKuqsOgyPdDObnSW7TlyPmKmc7b77de7 }}
          CF_ACCOUNT_ID: ${{ secrets.6fffa32a503ef35a744ef3243f4003f2 }}
        run: python cf-zt-cn-split.py
